declare -i n
declare -i x=$1
declare -i pr=$2
declare -i y
y=$x
y+=50000

export OMP_NUM_THREADS=1
export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/naveenk/my_programs/gcc-9/bin/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/home/naveenk/my_programs/gcc-9/bin/lib64:$LIBRARY_PATH
export CC=/home/naveenk/my_programs/gcc-9/bin/bin/gcc
export CXX=/home/naveenk/my_programs/gcc-9/bin/bin/g++


ion=nacl4mol
gmxexe=/home/naveenk/my_programs/gromacs-2020.4/bin/bin
dipolexe=/home/naveenk/my_programs/Dipole-Polarisability/build
inputfileloc=/home/naveenk/energytransfer/input/$ion
ensemblefileloc=/home/naveenk/energytransfer/input/mdp
restartfileloc=/home/naveenk/energytransfer/restarts/$ion
outputfileloc=/home/naveenk/energytransfer/simdata/$ion
ensemble=nve_pulse


for  (( i  = $x; i  <= $y; i += 19 ))
do
n=i
$gmxexe/gmx_d grompp -f $ensemblefileloc/$ensemble.mdp -c $restartfileloc/frame$i.gro -t $restartfileloc/frame$i.cpt -p $inputfileloc/topol.top -o $ensemble.tpr -maxwarn 5
$gmxexe/gmx_d  mdrun -v -deffnm $ensemble -nt 1
$gmxexe/gmx_d  trjconv -f $ensemble.trr -s $ensemble.tpr -n $inputfileloc/topol.ndx -o $ensemble.gro -ndec 7
a=$ensemble.gro
#sed -i 's/OW/O/g' $a
#sed -i 's/HW1/H/g' $a
#sed -i 's/HW2/H/g' $a

$dipolexe/exe $ensemble.gro traj.psf 100 32 15.00 328 120 /home/naveenk/my_programs/Dipole-Polarisability5/field_atomicunit  /home/naveenk/energytransfer/simdata/$ion/one$i /home/naveenk/energytransfer/simdata/$ion/two$i /home/naveenk/energytransfer/simdata/$ion/three$i /home/naveenk/energytransfer/simdata/$ion/four$i /home/naveenk/energytransfer/simdata/$ion/five$i

#$dipolexe/exe $ensemble.gro traj.psf 100 32 15.00 328 120 /home/naveenk/my_programs/Dipole-Polarisability5/field_atomicunit  /home/naveenk/energytransfer/simdata/$ion/one$i /home/naveenk/energytransfer/simdata/$ion/two$i /home/naveenk/energytransfer/simdata/$ion/three$i /home/naveenk/energytransfer/simdata/$ion/four$i /home/naveenk/energytransfer/simdata/$ion/five$i

#$dipolexe/exe $ensemble.gro traj.psf 100 32 15.6404 384 128 /home/naveenk/my_programs/Dipole-Polarisability4/field_atomicunit  $outputfileloc/one$i  $outputfileloc/two$i $outputfileloc/three$i  $outputfileloc/four$i
rm -rf *trr* *gro* *cpt*
rm rf *log* *xtc* *xvg*
rm -rf *mdout* *edr* *tpr* *sed*
done


##vmd -e PSF.tcl

#a=$ensemble.gro
#sed -i 's/OW/O/g' $a
#sed -i 's/HW1/H/g' $a
#sed -i 's/HW2/H/g' $a
#sed -i '/MW /d' $a
#sed -i ':a;N;$!ba;s/547\n generated by VMD/414\n generated by VMD/g' $a


##rm -rf \#*
#rm -rf *.mdp *.top *.grp



