declare -i n
declare -i x=$1
declare -i pr=$2
declare -i y
y=$x
y+=90000

ulimit -s unlimited
export OMP_NUM_THREADS=1
export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/naveenk/my_programs/gcc-9/bin/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/home/naveenk/my_programs/gcc-9/bin/lib64:$LIBRARY_PATH
export CC=/home/naveenk/my_programs/gcc-9/bin/bin/gcc
export CXX=/home/naveenk/my_programs/gcc-9/bin/bin/g++
export OMP_NUM_THREADS=1
export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH


ion=tmgcl2
tinkerexe=/home/naveenk/my_programs/tinkerhp/withfield
inputfileloc=/home/naveenk/energytransfer/input/$ion
outputfileloc=/home/naveenk/energytransfer/simdata/$ion
dipolexe=/home/naveenk/my_programs/Dipole-Polarisability/build
restartfileloc=/home/naveenk/energytransfer/restarts/$ion
ensemble=nvt

for  (( i  = $x; i  <= $y; i += 36 ))
do
n=i
rm water.dyn water.arc  water.xyz
cp $restartfileloc/frame$n.xyz  water.xyz
cp $restartfileloc/frame$n.dyn  water.dyn
cp $inputfileloc/md1.key  water.key
cp $inputfileloc/*.prm  .
cp $inputfileloc/field*  .

## TCF
$tinkerexe/dynamic.x water 5000 0.4 0.0004 1
$dipolexe/exe water.arc traj.psf 4998 0.4 15 327 125   /home/naveenk/energytransfer/simdata/$ion/all_velocities$i.dat /home/naveenk/energytransfer/simdata/$ion/one$i /home/naveenk/energytransfer/simdata/$ion/two$i /home/naveenk/energytransfer/simdata/$ion/three$i /home/naveenk/energytransfer/simdata/$ion/four$i /home/naveenk/energytransfer/simdata/$ion/five$i



## polarizability anistropy
#$tinkerexe/dynamic.x water 8000 0.4 0.032 1
#cp water.arc /home/naveenk/energytransfer/restarts/$ion/traj$i.arc
#$dipolexe/exe /home/naveenk/energytransfer/restarts/$ion/traj$i.arc traj.psf 100 32 15 327 125 /home/naveenk/my_programs/Dipole-Polarisability5/field_atomicunit  $outputfileloc/one$i  $outputfileloc/two$i $outputfileloc/three$i  $outputfileloc/four$i
done


##vmd -e PSF.tcl

#a=$ensemble.gro
#sed -i 's/OW/O/g' $a
#sed -i 's/HW1/H/g' $a
#sed -i 's/HW2/H/g' $a
#sed -i '/MW /d' $a
#sed -i ':a;N;$!ba;s/547\n generated by VMD/414\n generated by VMD/g' $a


##rm -rf \#*
#rm -rf *.mdp *.top *.grp



